### PR TITLE
Project Open Data & Sciencebase Catalog Archiving support

### PR DESCRIPTION
**Pull request by b5**
Ugh sorry I've left this open for a while, this is the code I've been using to archive POD data.json catalogs and sciencebase data catalogs. Both are defined as new types of tasks, and both leverage goroutines to crawl the catalogs in parallel, which makes the archiving process much more manageable time wise. I'd like to get this merged before the sprint if possible!

### CODE REVIEW

**Comment by b5** [comment]
I've also hijacked this PR to fulfill the Sprint prep checklist. This PR should:
* Update repo to new package names (`archive` -> `core`, etc.)
* Add stub `README.md`, moving old readme to readme_prev.md if it existed
* Add `.github` stuff: CONTRIBUTING, ISSUES
* Add support for codecov.io to CI tests
* confirm existence of a `LICENSE` file

**Comment by titaniumbones** [comment]
Not ignoring this! trying to find time to do at least a minimally
responsible review, but feel free to merge if you get tired of waiting!

b5 <notifications@github.com> writes:

> @b5 requested your review on: datatogether/task_mgmt#11 Project Open Data & Sciencebase Catalog Archiving support.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by dcwalk** [comment]
@b5 -- could you talk me through why are we moving to readme_prev? Are we eventually going to merge content back in?

**Review by dcwalk — APPROVED** [review]
From a cursory review I think the sprint prep side is covered, I cant speak to the pod implementation

**Comment by dcwalk** [comment]
RE: codecov error, here is the documentation: https://docs.codecov.io/docs/comparing-commits

I think we can just merge this into master, future PRs that branch off that should be able to have a comparison as the code coverage lines will be added to circle ci config...?

**Comment by dcwalk** [comment]
This PR should address #12  and https://github.com/datatogether/roadmap/issues/53

**Pull request merged**
